package com.mochisofts.mata.core.common

enum class ValidationError {
    CATEGORY_NAME_REQUIRED,
    CATEGORY_NAME_TOO_LONG,
    CATEGORY_COLOR_INVALID,
    CATEGORY_END_HOUR_INVALID,
    CATEGORY_NAME_DUPLICATE,
    TODO_TITLE_REQUIRED,
    TODO_TITLE_TOO_LONG,
    TODO_DESCRIPTION_TOO_LONG,
    TODO_DUE_TIME_INVALID,
    TODO_CATEGORY_NOT_FOUND,
    TODO_DATE_IN_PAST,
    TODO_END_DATE_BEFORE_START,
    TODO_RECURRENCE_RULE_INVALID,
    TODO_NOTIFICATION_TOO_MANY,
    TODO_NOTIFICATION_AMOUNT_INVALID,
    TODO_NOTIFICATION_DUPLICATE,
    TODO_NOTIFICATION_AFTER_REQUIRES_DEADLINE,
    TODO_NOTIFICATION_AFTER_DAY_END,
    TODO_ALREADY_ACTED,
    TODO_REQUIRED_COUNT_REACHED,
    TODO_NOT_FOUND,
    TODO_NOT_ACTIVE,
    TODO_ACTION_DATE_INVALID,
    TODO_ACTION_CANNOT_UNDO,
    HISTORY_RECORD_NOT_FOUND,
    HISTORY_ACTION_NOT_UNDOABLE,
}

class ValidationException(
    val error: ValidationError,
) : IllegalArgumentException()
